### ISSUE TITLE
Theme has changed in the jekyll serve demo, but doesn't change in github blog online

### ISSUE THREAD

**Issue by ss12f32v** [yous/whiteglass#4]
I really like this theme!
But i have some problem when i changing the theme.
It seems that the change shows in the local server by using jeykll server,but when i commit to the github. It doesn't work ,but the article and some title does change. I try to fix it, but still in vain.
Do you guys have some solution with this problem?
This is my blog's  link : https://ss12f32v.github.io/  
Thank you for making this awesome theme!

**Comment by ss12f32v** [comment]
Sorry for posting stupid question.
I have already solve the problem.
Thanks for this awesome theme!

**Comment by yous** [comment]
Hi, thanks for using this theme!

Actually, it takes some time to apply the changes on GitHub Pages. Also, this theme has [additional plugins](https://github.com/yous/whiteglass/blob/master/_config.yml), which are not [supported on GitHub Pages](https://help.github.com/articles/configuring-jekyll-plugins/), jekyll-archives and jekyll-paginate.

So you may use CI to build and push your blog automatically, that's why this theme also has [`.travis.yml`](https://github.com/yous/whiteglass/blob/master/.travis.yml). You may start from there by changing `env.global.secure` to your Travis CI token, `git clone`, `git push` commands, and some branch names. It builds `master` branch of this project and push to `gh-pages` branch.

Closing this now, please feel free to ask a question or make an issue!
